### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [BribroniumKazorvski/prj-rev-bwfs-dasmoto#4]
Great job with this project! It appears that you know how to style a page, link CSS, and arrange images. Great job! I can tell that you worked very hard on this project and it shows. Everything looks perfect to the design and there are no real big issues here. The only thing I would recommend here is to challenge yourself to make this a responsive site using media queries once you learn more about this topic in the later courses. Otherwise, great work on this.

Summary: Beyond Expectations

**Comment by BribroniumKazorvski** [comment]
Hey, thanks bro!
